version: '3'
services:
  db:
    image: mongo
    container_name: mongoDB
    
    ports:
    - "4000:27017"
    restart: always 

  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "3001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=chanmin
      - STORAGE_ACCESS_KEY=<애저 스토리지 액세스 키>
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "3002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
