version: '3'
services:

  db:
    image: mongo:4.2.8
    container_name: db
    ports:
     - "3000:27017"
    restart: always

  azure-storage:
    image: azure-storage
    build: 
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "3001:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=spacesangsoo
      - STORAGE_ACCESS_KEY=feMHnftP2khr+fzcHHV83NPUv1mVXRbkhpWptCPvZO/Hpo58cnAWGUKjE3PGljV4fWdTyjxJZwepRms4pBygRw==
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "3002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://db:27017
      - DBNAME=video-streaming
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    depends_on:
      - db
    restart: "no"
