version: '3'
services:

  azure-storage:
    image: azure-storage
    build:
      context: ./azure-storage
      dockerfile: Dockerfile
    container_name: azure-storage
    ports:
      - "3000:80"
    environment:
      - PORT=80
      - STORAGE_ACCOUNT_NAME=spacesangsoo
      - STORAGE_ACCESS_KEY=feMHnftP2khr+fzcHHV83NPUv1mVXRbkhpWptCPvZO/Hpo58cnAWGUKjE3PGljV4fWdTyjxJZwepRms4pBygRw==
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "3001:80"
    environment:
      - PORT=80
      - VIDEO_STORAGE_HOST=video-storage
      - VIDEO_STORAGE_PORT=80
    restart: "no"
